name: Generate Snake

on:
  schedule:
    # Запускается каждые 12 часов
    - cron: "0 */12 * * *"
  workflow_dispatch: # Позволяет запускать вручную

permissions:
  contents: write # Даём права на создание ветки и пуш

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Pipotka
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?color_snake=#ff79c6&color_dots=#282a36,#44475a,#6272a4,#bd93f9,#ff79c6
            
      - name: Push to output branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
